#!/bin/bash
set -Eeuo pipefail

# Ensure mandatory env vars are set
require_env() {
    for var in "$@"; do
    if [[ -z "${!var:-}" ]]; then
        echo "ERROR: Environment variable '$var' is not set" >&2
        exit 1
    fi
    done
}
require_env POSTGRES_USER POSTGRES_PASSWORD DB_POSTGRES_NAME \
            DB_MARKET_NAME DB_SYS_NAME DB_SYS_USER DB_SYS_PASSWORD \
            DB_TEST_USER DB_TEST_PASSWORD

export PGPASSWORD="$POSTGRES_PASSWORD"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DB_POSTGRES_NAME" <<-EOSQL
    CREATE DATABASE $DB_MARKET_NAME;
    CREATE DATABASE $DB_SYS_NAME;
    CREATE USER $DB_SYS_USER WITH CREATEDB PASSWORD '$DB_SYS_PASSWORD';
    -- Grant DB ownership/privileges instead of SUPERUSER
    GRANT ALL PRIVILEGES ON DATABASE $DB_MARKET_NAME TO $DB_SYS_USER;
    GRANT ALL PRIVILEGES ON DATABASE $DB_SYS_NAME TO $DB_SYS_USER;
    CREATE USER $DB_TEST_USER WITH PASSWORD '$DB_TEST_PASSWORD';
EOSQL

psql -v ON_ERROR_STOP=1 --username "$DB_SYS_USER" --dbname "$DB_MARKET_NAME" <<-EOSQL
    GRANT USAGE ON SCHEMA public TO $DB_TEST_USER;
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO $DB_TEST_USER;
    -- Optional: sequences if inserts are needed
    -- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $DB_TEST_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $DB_TEST_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$DB_SYS_USER" --dbname "$DB_SYS_NAME" <<-EOSQL
    GRANT USAGE ON SCHEMA public TO $DB_TEST_USER;
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO $DB_TEST_USER;
    -- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $DB_TEST_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $DB_TEST_USER;
EOSQL
