#!/bin/bash
set -e

export PGPASSWORD="$POSTGRES_PASSWORD"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DB_POSTGRES_NAME" <<-EOSQL
    CREATE DATABASE $DB_MARKET_NAME;
    CREATE DATABASE $DB_SYS_NAME;
    CREATE USER $DB_SYS_USER WITH CREATEDB PASSWORD '$DB_SYS_PASSWORD';
    ALTER USER $DB_SYS_USER SUPERUSER;
    CREATE USER $DB_TEST_USER WITH PASSWORD '$DB_TEST_PASSWORD';
EOSQL

psql -v ON_ERROR_STOP=1 --username "$DB_SYS_USER" --dbname "$DB_MARKET_NAME" <<-EOSQL
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $DB_TEST_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$DB_SYS_USER" --dbname "$DB_SYS_NAME" <<-EOSQL
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $DB_TEST_USER;
EOSQL
